/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleModal: typeof import('./src/components/ArticleModal.vue')['default']
    CouponModal: typeof import('./src/components/CouponModal.vue')['default']
    DelModal: typeof import('./src/components/DelModal.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    OrderModal: typeof import('./src/components/OrderModal.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    PaginationComponent: typeof import('./src/components/PaginationComponent.vue')['default']
    ProductModal: typeof import('./src/components/ProductModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
